[tool.black]
line-length = 120
force-exclude = "scripts"

[tool.isort]
line_length = 120
extend_skip = ["scripts"]
profile = "black"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools[toml]>=3.4"]
build-backend = "setuptools.build_meta"
